### ISSUE TITLE
No images for questions

### ISSUE THREAD

**Issue by hnasheralneam** [zenith-hacks/zenith#10]
Not sure if this is intentional, but there are no images in the questions section.
![image](https://github.com/user-attachments/assets/f54e503c-47da-476d-809d-364d8707c9ed)

**Comment by hnasheralneam** [comment]
Fixed in new branch

**Comment by iamawatermelo** [comment]
Don't close until merged (GitHub automatically does this for you when it is merged and referenced in a commit)
