### ISSUE TITLE
Add all sponsors

### ISSUE THREAD

**Issue by hnasheralneam** [zenith-hacks/zenith#11]
We need to add all the sponsors from the old site. They also need links to the website. Also needs some formatting changes. I'll take this.

**Comment by hnasheralneam** [comment]
I know you wanted to have only SVGs, but that's not really possible right now, and if this is going to be the official website, it needs all the sponsors.

**Comment by hnasheralneam** [comment]
Some don't look great, but I mean they are giving us free stuff. Fixed in new branch.

**Comment by iamawatermelo** [comment]
> I know you wanted to have only SVGs, but that's not really possible right now, and if this is going to be the official website, it needs all the sponsors.

Alright. Re-opening for reason mentioned in #10
